<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ServiceController extends Controller
{
    /**
     * Display the services management page (mounts Livewire component).
     */
    public function index()
    {
        return view('admin.services.index');
    }

    /**
     * Redirect create to index since the form is handled on the index page (Livewire).
     */
    public function create()
    {
        // route name generated by the resource is `services.index` (under the admin prefix)
        return Redirect::route('services.index');
    }

    // The resource routes for store/edit/update/destroy are managed by Livewire in the
    // admin.services.index view. Provide safe passthroughs to avoid 500 on direct calls.
    public function store(Request $request)
    {
        return Redirect::back();
    }

    public function edit($id)
    {
        return Redirect::route('services.index');
    }

    public function update(Request $request, $id)
    {
        return Redirect::back();
    }

    public function destroy($id)
    {
        return Redirect::back();
    }
}
